version: 2

models:
  - name: stg_customers
    description: "Cleaned customer data."
    columns:
      - name: customer_id
        description: "The primary key for customers."
        tests:
          - unique
          - not_null
      - name: account_status
        description: "Status of the account."
        tests:
          - accepted_values:
              values: ['active', 'suspended', 'churned']

  - name: stg_usage_logs
    description: "Cleaned usage transactions."
    columns:
      - name: log_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
          # This ensures every log belongs to a real customer in the customers table
          - relationships:
              to: ref('stg_customers')
              field: customer_id
